### ISSUE TITLE
link to talks

### ISSUE THREAD

**Issue by divarvel** [ScalaIO/scala.io_web_main#2]
When promoting scala.io, I often want to point to specific talks.

Right now it looks like it's impossible to have a URL for a specific talk : talks don't have dedicated pages and in the talks list, talks don't have ids.

It'd be great to have at least an id for each talk in the talk list.

**Comment by GabrielKast** [comment]
J'ai demandé à Nico, voilà sa réponse:

Il y a bien un ID par talk, c’est l’id de Proposal. 
Par exemple : http://cfp.devoxx.fr/devoxxfr2014/talk/BBV-277
S’il s’agit de la partie programme, je ne sais pas ce que Jean a utilisé, s’il a développé quelque chose de particulier
ou s’il a adapté la partie Publisher. Je n’ai plus de nouvelles depuis juin donc j’imagine que tout va bien.

Voili voilou

**Comment by jeantil** [comment]
Euh le problème là c'était de faire en sorte qu'on puisse avoir un lien direct sur la description du talk _sur le site web de scala.io_
J'ai effectivement utilisé l'id du talk et mis des ancres en place pour chaque talk dans la liste des talks.
Le titre du talk est également un lien vers l'ancre du talk. Du coup il suffit de copier ce lient et on peut le partager (par exemple sur twitter) 
Si qqun clique dessus il arrivera directement sur la description du talk sur la liste des talks, sans avoir a scroller.
